name: Refresh publications
on:
  schedule:
    - cron: "0 6 1 * *"   # first day of every month at 06:00 UTC
  workflow_dispatch: {}   # allows manual trigger
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  update-publications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Update publications
        run: python scripts/update_publications.py

      - name: Inline publications into index.html
        run: |
          START="<!-- PUBS:START -->"
          END="<!-- PUBS:END -->"
          if [ -f data/publications.html ]; then
            # Create a temporary file with the publication content
            PUBS_CONTENT=$(cat data/publications.html)
            # Use perl to replace the content between markers
            perl -0777 -pe "s/\Q${START}\E.*?\Q${END}\E/${START}\n${PUBS_CONTENT}\n${END}/s" -i index.html
          fi

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/publications.json data/publications.html index.html
          git commit -m "chore: auto-refresh publications data [skip ci]"
          git push